from enum import StrEnum


class RowStatus(StrEnum):
    DRAFT = "DRAFT"
    WAITING_IMAGES = "WAITING_IMAGES"
    UPLOADING = "UPLOADING"
    READY = "READY"
    DEBOUNCING = "DEBOUNCING"
    QUEUED = "QUEUED"
    ANALYZING = "ANALYZING"
    VALIDATING = "VALIDATING"
    REPAIRING = "REPAIRING"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELING = "CANCELING"
    CANCELED = "CANCELED"
    DIRTY = "DIRTY"


class JobStatus(StrEnum):
    PENDING_DISPATCH = "PENDING_DISPATCH"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    VALIDATING = "VALIDATING"
    REPAIRING = "REPAIRING"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"


ACTIVE_JOB_STATUSES = frozenset(
    {
        JobStatus.PENDING_DISPATCH,
        JobStatus.QUEUED,
        JobStatus.RUNNING,
        JobStatus.VALIDATING,
        JobStatus.REPAIRING,
        JobStatus.CANCEL_REQUESTED,
    }
)
TERMINAL_JOB_STATUSES = frozenset(JobStatus) - ACTIVE_JOB_STATUSES
